; Vhost configuration
[vhost.start]
    server_name = example.com           ; Domain name
    host = 127.0.0.1                    ; IPv4 address the vhost binds to
    listen = 9898                       ; Port the vhost listens from
    max_body_size = 1048576             ; Max body size for this vhost
    keep_alive_timeout = 30             ; Idle timeout in seconds (default: 60)
    error_page = 404 /var/www/errors/404.html  ; Custom error pages for this vhost
    error_page = 500 /var/www/errors/500.html
    error_page = 403 /var/www/errors/403.html
    cgi  = .py	/usr/bin/python3	    ; Extension mapped to interpreter or executable that will run the reuqested file
    cgi  = .php /usr/bin/php8.1		    ;

    ; Root location
    [location.start]
        path = /                        ; Path to match
        root = /var/www/example         ; Folder in which to look for files (root+path)
        methods = GET                   ; Allowed request methods on the routes encompassed by this location block
        default = index index.html index.htm  ; Default files to serve when a directory is requested without specific file request
    [location.end]

    ; Uploading
    [location.start]
        path = /files                   ; Path to match
        root = /var/www/example		    ; Folder in which to look for files (root+path)
        methods = GET POST DELETE       ; Only allow GET for directory listings
        max_body_size = 100             ; Max body size for this vhost
        upload_store = /tmp/www/example/files/uploads  ; Allow uploads in routes encompassed by this location block
        default = index index.html index.htm  ; Default files to serve when a directory is requested without specific file request
    [location.end]

    ; Directory listing
    [location.start]
        path = /files/uploads           ; Path to match
        root = /var/www/example		    ; Folder in which to look for files (root+path)
        methods = GET                   ; Only allow GET for directory listings
        autoindex = true                ; Generate a directory listing when no default file is present
    [location.end]

    ; Redirection
    [location.start]
        path = /old/page                ; Path to match
        return = 308 /var/www/new/page  ; Redirection code and file to serve instead of path
    [location.end]
[vhost.end]
