; Vhost configuration
[vhost.start]
    server_name = example.com           ; Domain name
    host = 127.0.0.1                    ; IPv4 address the vhost binds to
    listen = 9898                       ; Port the vhost listens from
    max_body_size = 1048576             ; Max body size for this vhost
    error_page = 404 /var/www/errors/404.html  ; Custom error pages for this vhost
    error_page = 500 /var/www/errors/500.html
    error_page = 403 /var/www/errors/403.html

    ; Root location
    [location.start]
        path = /                        ; Path to match
        root = /var/www/example         ; Folder in which to look for files (root+path)
        methods = GET POST              ; Allowed request methods on the routes encompassed by this location block
        defaults = index index.html index.htm  ; Default files to serve when a directory is requested without specific file request
    [location.end]

    ; Directory listing (autoindex) and uploading
    [location.start]
        path = /files                   ; Path to match
        root = /var/www/example		    ; Folder in which to look for files (root+path)
        methods = GET POST DELETE       ; Only allow GET for directory listings
        autoindex = true                ; Generate a directory listing when no default file is present
        upload_store = /tmp/www/example/files/uploads  ; Allow uploads in routes encompassed by this location block
    [location.end]

    ; Redirection
    [location.start]
        path = /old-page                ; Path to match
        root = /var/www/example         ; Folder in which to look for files (root+path)
        redirect = 308 /new-page        ; Redirection code and file to serve instead of path
    [location.end]

    ; CGI Execution
    [location.start]
        path = /cgi-bin/                ; Path to match
        root = /var/www/example 	    ; Folder in which to look for files (root+path)
        cgi  = .py	/usr/bin/python3	; Extension mapped to interpreter or executable that will run the reuqested file
		cgi  = .php /usr/bin/php8.1		;
        methods = GET POST              ; Allowed methods on the locations encompassed by this location block
    [location.end]
[vhost.end]
