[vhost.start]
    server_name = bodylimit.com         ; Domain name
    host = 127.0.0.1                    ; IPv4 address the vhost binds to
    listen = 8989                       ; Port the vhost listens from
    error_page = 404 /var/www/bodylimit/errors/404.html  ; Custom error pages for this instance

    [location.start]
        path = /                        ; Path to match
        root = /var/www/bodylimit       ; Folder in which to look for files (root+path)
        methods = GET POST              ; Allowed methods on the routes encompassed by this location block
        max_body_size = 10              ; Body size for this location
        default = index index.html index.htm   ; Default files to serve when a directory is requested without specific file request
    [location.end]
[vhost.end]