[vhost.start]
    server_name = localhost
    host = 127.0.0.1
    listen = 8080
    cgi = .bla ./cgi_tester

    [location.start]
        path = /
        root = ./www/YoupiBanane
        methods = GET
        default = index index.html
    [location.end]

    [location.start]
        path = /post_body
        root = ./www/YoupiBanane
        methods = POST
        max_body_size = 100
    [location.end]

    [location.start]
        path = /directory
        root = ./www/YoupiBanane
        methods = GET POST
        max_body_size = 100000000
        default = youpi.bad_extension
    [location.end]
[vhost.end]
